[package]
name = "rsincron"
authors = ["Mattia Repetto <mfwre-gh@proton.me>"]
version = "0.0.9"
edition = "2021"
repository = "https://github.com/mfwre/rsincron"
homepage = "https://github.com/mfwre/rsincron"
documentation = "https://github.com/mfwre/rsincron"
license = "GPL-3.0-or-later"
description = "Rust rewrite of the incredibly useful but abandoned incron software"
readme = "README.md"
keywords = ["incron"]

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["derive"] }
fern = "0.6.1"
figment = { version = "0.10.8", features = ["toml"] }
futures = "0.3.26"
inotify = "0.10.0"
log = { version = "0.4.17", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
uuid = { version = "1.3.0", features = ["v4"] }
walkdir = "2.3.2"

[[bin]]
name = "rsincrontab"

[[bin]]
name = "rsincrond"

[lib]
name = "rsincronlib"
