[package]
name = "rsincron"
authors = ["Mattia Repetto <mfwre-gh@proton.me>"]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/mfwre/rsincron"
homepage = "https://github.com/mfwre/rsincron"
documentation = "https://github.com/mfwre/rsincron"
license = "GPL-3.0-or-later"
description = "Rust rewrite of the incredibly useful but abandoned incron software"
readme = "README.md"
keywords = ["incron"]

[dependencies]
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["derive"] }
fern = "0.6.1"
log = "0.4.17"
uuid = { version = "1.3.0", features = ["v4"] }

[[bin]]
name = "rsincrontab"

[lib]
name = "rsincronlib"
